version: "3.9"
services:
  web1:
    build: ./backend/Model
    container_name: backend
    ports: 
      - "5000:8050"
  web2:
    build: ./frontend/interface
    container_name: frontend
    ports: 
      - "8050:8050"

#To make changes must delete dsa3101-2210-13-lta_web1/dsa3101-2210-13-lta_web2 under images
